### ISSUE TITLE
Deployment to Chrome store is failing with 400 error

### ISSUE THREAD

**Issue by NoxHarmonium** [agiledigital/mule-preview-browser-extension#94]
Deployment is failing due to:

```
[11:10:16 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[11:10:16 PM] [semantic-release] › ✖  An error occurred while running semantic-release: ErrorClass [HTTPError]: Response code 400 (Bad Request)
    at /home/circleci/repo/node_modules/got/index.js:123:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'www.googleapis.com',
  hostname: 'www.googleapis.com',
  method: 'POST',
  path: '/chromewebstore/v1.1/items/mgglinkjbpmncolojlkopolokmcnneil/publish?publishTarget=trustedTesters',
  statusCode: 400,
  statusMessage: 'Bad Request',
  pluginName: 'semantic-release-chrome'
}
ErrorClass [HTTPError]: Response code 400 (Bad Request)
    at /home/circleci/repo/node_modules/got/index.js:123:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'www.googleapis.com',
  hostname: 'www.googleapis.com',
  method: 'POST',
  path: '/chromewebstore/v1.1/items/mgglinkjbpmncolojlkopolokmcnneil/publish?publishTarget=trustedTesters',
  statusCode: 400,
  statusMessage: 'Bad Request',
  pluginName: 'semantic-release-chrome'
}
```

https://app.circleci.com/pipelines/github/agiledigital/mule-preview-browser-extension/101/workflows/4cc03462-09fb-4a5d-bea7-63adb1be9d2b/jobs/115

**Comment by NoxHarmonium** [comment]
Looks like there was some required information I needed to fill out in the Web Store admin page. I'm trying deployment again to see how it goes.

**Comment by NoxHarmonium** [comment]
Deployment is working again after I filled in the missing information
